Task 1

In [ ]:
import numpy as np;
a = np.empty((2,2));
print(a);

[[ 4.75635831e-310  0.00000000e+000]
 [-1.71255581e+276  6.79649740e-310]]


In [ ]:
a = np.ones((4,2));
print(a);

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.full((4,4),7);
print(a);

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
a= np.zeros_like([[5, 6], [7, 8]]);
print(a);

[[0 0]
 [0 0]]


In [ ]:
a= np.ones_like([[5, 6], [7, 8]]);
print(a);

[[1 1]
 [1 1]]


In [ ]:
new_list = [1, 2, 3, 4];
a = np.array(new_list);
print(a);

[1 2 3 4]


Task 2

In [ ]:
a= np.arange(10,49);
print(a);

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
a= np.arange(0,9).reshape(3,3);
print(a);

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a= np.eye(3,3);
print(a);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean = random_array.mean()
print( random_array)
print("Mean of the random array:", mean)

[0.00414414 0.67594215 0.22619206 0.45628538 0.26331109 0.55900905
 0.30105708 0.11004725 0.41136684 0.24102269 0.22623273 0.81878261
 0.17021428 0.69061992 0.20801157 0.9337828  0.72447151 0.73310194
 0.20029536 0.75463777 0.46255109 0.41536818 0.85542641 0.32200681
 0.73669946 0.65696098 0.02762849 0.75383245 0.51867306 0.37261893]
Mean of the random array: 0.46100980330169433


In [ ]:
random_array = np.random.random((10,10))
max = random_array.max()
min = random_array.min()
print( random_array)
print("Maximum:", max)
print("Minimum:", min)

[[0.21144362 0.09109918 0.70075323 0.29830649 0.07092373 0.75009114
  0.5725973  0.02808689 0.04841254 0.58744029]
 [0.75226777 0.02536689 0.39893967 0.12686829 0.35945345 0.85320789
  0.37667812 0.34137707 0.88478899 0.10397099]
 [0.69852057 0.59772968 0.49830004 0.7672794  0.54709347 0.35774606
  0.71688804 0.3431262  0.319358   0.27212754]
 [0.66047402 0.83519885 0.63207063 0.87853035 0.17524919 0.47350499
  0.95427784 0.03027144 0.15531611 0.0783627 ]
 [0.597506   0.82791689 0.69602286 0.845579   0.69166226 0.84684008
  0.79516347 0.32619153 0.29087538 0.86690807]
 [0.29616133 0.61075024 0.90370589 0.29643221 0.73585004 0.21590635
  0.62836257 0.80000017 0.46019037 0.82541574]
 [0.21297579 0.00821075 0.93198283 0.81923871 0.83580214 0.72828281
  0.27949586 0.3390934  0.11829855 0.39642481]
 [0.59785312 0.02004946 0.83478634 0.69569552 0.93826461 0.24679709
  0.37553161 0.81759024 0.43867961 0.25371635]
 [0.56921897 0.65267127 0.266624   0.00872663 0.09608917 0.58564483
  0.84680882

In [ ]:
zero_array = np.zeros(10)
print("before repacing", zero_array)
zero_array[4] = 1
print("afre repacing", zero_array)

before repacing [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
afre repacing [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
reversed_arr= np.array(arr)[::-1]
print(reversed_arr)

In [ ]:
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print( arr)


2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Fill black squares for odd rows
checkerboard[::2, 1::2] = 1  # Fill black squares for even rows
print("\n8x8 matrix with a checkerboard pattern:\n", checkerboard)


8x8 matrix with a checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Task 3


In [ ]:
import numpy as np;
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]);
w = np.array([11,12]);

In [ ]:
add= np.add(x,y);
print("add:", add)
sub= np.subtract(x,y);
print("sub:", sub)
mul=np.multiply(4,x);
print("mul:", mul)
square_x= np.power(x,2);
print("square of x:", square_x)
square_y= np.power(y,2);
print("square of y:", square_y)
square_v= np.power(v,2);
print("square of v:", square_v)
square_w= np.power(w,2);
print("square of w:", square_w)




add: [[ 6  8]
 [10 13]]
sub: [[-4 -4]
 [-4 -3]]
mul: [[ 4  8]
 [12 20]]
square of x: [[ 1  4]
 [ 9 25]]
square of y: [[25 36]
 [49 64]]
square of v: [ 81 100]
square of w: [121 144]


In [ ]:
dot_vw = np.dot(v, w)
print("dot product of v and w", dot_vw)
dot_xv = np.dot(x, v)
print("dot product of x and v", dot_xv)
dot_xy = np.dot(x, y)
print("dot product of x and y", dot_xy)

In [ ]:
concat_xy_row = np.concatenate((x, y))
print(concat_xy_row)
concat_vw_col = np.vstack((v, w)).T
print(concat_vw_col)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
concat_xv= np.concatenate((x,v))
print(concat_xv)
# This error here occured due to the difference in number of dimensions of the respective arrays. All the input arrays must have same number of dimension. x has 2 dimension(s) whereas v has 1 dimension(s).

Task 4

In [ ]:
A = np.array([[3,4],[7,8]]);
B = np.array([[5,3],[2,1]]);
#A.A−1 = I.
inverse_A= np.linalg.inv(A);
dot_p=np.dot(A,inverse_A);
print(dot_p);

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False


In [ ]:
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", BT_AT)
print("Equality Check:", np.array_equal(AB_transpose, BT_AT))

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Equality Check: True


In [ ]:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# converting to matrix form:
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B = np.array([-1, -3, 9])
# X=A^-1.B
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution (X):\n", X)

Solution (X):
 [ 2.  1. -2.]


Task 4.2

In [ ]:
import numpy as np
import time

size=1000000;
list1=[i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)

# 1. Element-wise Addition
start_time=time.time()
list_add= [list1[i]+list2[i] for i in range(size)]
list_time=time.time()-start_time;

start_time = time.time()
array_addition = array1 + array2
array_time = time.time() - start_time
print(f"1. Element-wise Addition:")
print(f"   Time with Python lists: {list_time:.6f} seconds")
print(f"   Time with NumPy arrays: {array_time:.6f} seconds")

# 2. Element-wise Multiplication
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start_time

start_time = time.time()
array_multiplication = array1 * array2
time_array_mul = time.time() - start_time

print(f"2. Element-wise Multiplication:")
print(f"   Time with Python lists: {time_list_mul:.6f} seconds")
print(f"   Time with NumPy arrays: {time_array_mul:.6f} seconds")

# 3. Dot Product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start_time

start_time = time.time()
dot_product_array = np.dot(array1, array2)
time_array_dot = time.time() - start_time

print(f"3. Dot Product:")
print(f"   Time with Python lists: {time_list_dot:.6f} seconds")
print(f"   Time with NumPy arrays: {time_array_dot:.6f} seconds")

# 4. Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start_time = time.time()
list_result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
time_list_matrix_mul = time.time() - start_time

start_time = time.time()
array_result = np.multiply(array_matrix1, array_matrix2)
time_array_matrix_mul = time.time() - start_time

print(f"4. Matrix Multiplication:")
print(f"   Time with Python lists: {time_list_matrix_mul:.6f} seconds")
print(f"   Time with NumPy arrays: {time_array_matrix_mul:.6f} seconds")

0.15254855155944824
   Time with NumPy arrays: 0.026264 seconds
